import type { Metadata } from 'next';
import './globals.css';
import '@/app/styles/main.scss';
import Providers from './providers';
export const metadata: Metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app + Mantine UI',
};

export default async function RootLayout({
  children,
  // params,
}: {
  children: React.ReactNode;
  // params: Promise<{ team: string }>;
}) {
  // const { team } = await params;
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
